name: "官方版编译玩客云三代 Armbian"
on:
  workflow_dispatch:
     inputs:
      branch_version:
        type: choice
        description: 选择源码分支
        required: true
        default: "main"
        options:
        - v25.11.0-trunk.457
        - v25.11.0-trunk.414
        - v25.11.0-trunk.382
        - v25.8.1
        - main
        
jobs:
  armbian_build_core:
    name: armbian-"${{ matrix.RELEASE }}"-"${{ matrix.TYPE }}"-固件编译
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        RELEASE:
          # - focal # Ubuntu 20.04 LTS
          # - jammy # Ubuntu 22.04 LTS
          #- noble # Ubuntu 24.04 LTS
          #- oracular # Ubuntu 24.10
          #- plucky # Ubuntu 25.04
          # - buster # Debian 10
          - bullseye # Debian 11
          - bookworm # Debian 12
          - trixie # Debian 13
          #- sid # Debian unstable
        TYPE:
          - minimal
          - server
          #- xfce
          
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "${{ matrix.RELEASE }}"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "onecloud"                   # build target
          armbian_branch:    "${{ inputs.branch_version }}"
          armbian_kernel_branch:    "current"
          armbian_ui:               "${{ matrix.TYPE }}"
          armbian_release_tittle:   "玩客云三代(WS1608) Armbian镜像"

